### ISSUE TITLE
改正案：第七条「他人の性的好奇心を満たす目的で特定少数に見せる場合は？」

### ISSUE THREAD

**Issue by next49** [next49/cplj#3]
第一項と第五項を読む限り、「他人の性的好奇心を満たす目的で特定少数に見せる場合」は問題ないように読めるけど大丈夫？

第七条第一項

> 自己の性的好奇心を満たす目的で、児童ポルノを所持した者は、一年以下の懲役又は百万円以下の罰金に処する。自己の性的好奇心を満たす目的で、第二条第三項各号のいずれかに掲げる児童の姿態を視覚により認識することができる方法により描写した情報を記録した電磁的記録を保管した者も、同様とする。

第七条第五項

> 児童ポルノを不特定若しくは多数の者に提供し、又は公然と陳列した者は、五年以下の懲役若しくは五百万円以下の罰金に処し、又はこれを併科する。電気通信回線を通じて第二条第三項各号のいずれかに掲げる児童の姿態を視覚により認識することができる方法により描写した情報を記録した電磁的記録その他の記録を不特定又は多数の者に提供した者も、同様とする。

**Comment by vzvu3k6k** [comment]
その場合には、[改正案第七条](https://github.com/next49/cplj/blob/244304de3e2b2125abf8f52bbfee944528da6f77/cplj.md#-16)二項（現行法の第七条一項）「児童ポルノを提供した者は、三年以下の懲役又は三百万円以下の罰金に処する。…」が適用されるので、罰することは可能だと思います。

**Comment by next49** [comment]
確かにおっしゃるとおりですね。私の誤読でした。
